POST http://localhost:8000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "11111111"
}


### friend request 

POST http://localhost:8000/request-connection/email@gmail.com
Content-Type: application/json

{
    "connectToId": "4b3cf381d7af9110d48b2585" 
}

###
POST http://localhost:8000/add-friend/email@gmail.com
Content-Type: application/json

{
    "connectToId": "4b3cf381d7af9110d48b2585" 
}

###
GET http://localhost:8000/get



###

GET http://localhost:8000/get-connection-list/email@gmail.com

###
GET http://localhost:8000/get-requests-list/just@gmail.com


###
GET http://localhost:8000/view-profile/null/just@gmail.com



###
put http://localhost:8000/change-password/just@gmail.com
content-type: application/json

{
  "oldPassword" :  "hello123",
  "newPassword" : "hello123"
}